# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_files_ignorable.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data_files_ignorable.proto',
  package='maia',
  syntax='proto2',
  serialized_pb=_b('\n\x1a\x64\x61ta_files_ignorable.proto\x12\x04maia\"v\n\x10IgnorableGameSet\x12\x11\n\tnum_games\x18\x01 \x01(\x07\x12+\n\ngame_infos\x18\x02 \x03(\x0b\x32\x17.maia.IgnorableGameInfo\x12\"\n\x05moves\x18\x03 \x03(\x0b\x32\x13.maia.IgnorableMove\"\xc1\x01\n\x11IgnorableGameInfo\x12\x0f\n\x07game_id\x18\x01 \x01(\t\x12\x14\n\x0cwhite_player\x18\x02 \x01(\t\x12\x14\n\x0c\x62lack_player\x18\x03 \x01(\t\x12\x11\n\twhite_elo\x18\x04 \x01(\x07\x12\x11\n\tblack_elo\x18\x05 \x01(\x07\x12\x0f\n\x07num_ply\x18\x06 \x01(\x07\x12\x11\n\ttimestamp\x18\x07 \x01(\x07\x12\x12\n\nstart_time\x18\x08 \x01(\x07\x12\x11\n\tincrement\x18\t \x01(\x07\"\xca\x01\n\rIgnorableMove\x12\x10\n\x08is_white\x18\x01 \x01(\x08\x12\x12\n\nactive_won\x18\x02 \x01(\x08\x12\x11\n\tno_winner\x18\x03 \x01(\x08\x12\x13\n\x0bignore_move\x18\x04 \x01(\x08\x12\x10\n\x08move_ply\x18\x05 \x01(\x07\x12\r\n\x05\x62oard\x18\x06 \x01(\t\x12\x0c\n\x04move\x18\x07 \x01(\t\x12\x11\n\tmove_time\x18\x08 \x01(\x07\x12\x16\n\x0epre_move_clock\x18\t \x01(\x07\x12\x11\n\topp_clock\x18\n \x01(\x07')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_IGNORABLEGAMESET = _descriptor.Descriptor(
  name='IgnorableGameSet',
  full_name='maia.IgnorableGameSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_games', full_name='maia.IgnorableGameSet.num_games', index=0,
      number=1, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='game_infos', full_name='maia.IgnorableGameSet.game_infos', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='moves', full_name='maia.IgnorableGameSet.moves', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=154,
)


_IGNORABLEGAMEINFO = _descriptor.Descriptor(
  name='IgnorableGameInfo',
  full_name='maia.IgnorableGameInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='game_id', full_name='maia.IgnorableGameInfo.game_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='white_player', full_name='maia.IgnorableGameInfo.white_player', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='black_player', full_name='maia.IgnorableGameInfo.black_player', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='white_elo', full_name='maia.IgnorableGameInfo.white_elo', index=3,
      number=4, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='black_elo', full_name='maia.IgnorableGameInfo.black_elo', index=4,
      number=5, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_ply', full_name='maia.IgnorableGameInfo.num_ply', index=5,
      number=6, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='maia.IgnorableGameInfo.timestamp', index=6,
      number=7, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start_time', full_name='maia.IgnorableGameInfo.start_time', index=7,
      number=8, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='increment', full_name='maia.IgnorableGameInfo.increment', index=8,
      number=9, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=350,
)


_IGNORABLEMOVE = _descriptor.Descriptor(
  name='IgnorableMove',
  full_name='maia.IgnorableMove',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_white', full_name='maia.IgnorableMove.is_white', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='active_won', full_name='maia.IgnorableMove.active_won', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='no_winner', full_name='maia.IgnorableMove.no_winner', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ignore_move', full_name='maia.IgnorableMove.ignore_move', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='move_ply', full_name='maia.IgnorableMove.move_ply', index=4,
      number=5, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='board', full_name='maia.IgnorableMove.board', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='move', full_name='maia.IgnorableMove.move', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='move_time', full_name='maia.IgnorableMove.move_time', index=7,
      number=8, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pre_move_clock', full_name='maia.IgnorableMove.pre_move_clock', index=8,
      number=9, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='opp_clock', full_name='maia.IgnorableMove.opp_clock', index=9,
      number=10, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=353,
  serialized_end=555,
)

_IGNORABLEGAMESET.fields_by_name['game_infos'].message_type = _IGNORABLEGAMEINFO
_IGNORABLEGAMESET.fields_by_name['moves'].message_type = _IGNORABLEMOVE
DESCRIPTOR.message_types_by_name['IgnorableGameSet'] = _IGNORABLEGAMESET
DESCRIPTOR.message_types_by_name['IgnorableGameInfo'] = _IGNORABLEGAMEINFO
DESCRIPTOR.message_types_by_name['IgnorableMove'] = _IGNORABLEMOVE

IgnorableGameSet = _reflection.GeneratedProtocolMessageType('IgnorableGameSet', (_message.Message,), dict(
  DESCRIPTOR = _IGNORABLEGAMESET,
  __module__ = 'data_files_ignorable_pb2'
  # @@protoc_insertion_point(class_scope:maia.IgnorableGameSet)
  ))
_sym_db.RegisterMessage(IgnorableGameSet)

IgnorableGameInfo = _reflection.GeneratedProtocolMessageType('IgnorableGameInfo', (_message.Message,), dict(
  DESCRIPTOR = _IGNORABLEGAMEINFO,
  __module__ = 'data_files_ignorable_pb2'
  # @@protoc_insertion_point(class_scope:maia.IgnorableGameInfo)
  ))
_sym_db.RegisterMessage(IgnorableGameInfo)

IgnorableMove = _reflection.GeneratedProtocolMessageType('IgnorableMove', (_message.Message,), dict(
  DESCRIPTOR = _IGNORABLEMOVE,
  __module__ = 'data_files_ignorable_pb2'
  # @@protoc_insertion_point(class_scope:maia.IgnorableMove)
  ))
_sym_db.RegisterMessage(IgnorableMove)


# @@protoc_insertion_point(module_scope)
